name: Build Launcher (Multi-Platform)

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., 2.0.0)'
        required: true
        default: '2.0.0'

permissions:
  contents: write
  actions: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd biosync-launcher
          npm ci || npm install

      - name: Build React app
        run: |
          cd biosync-launcher
          npm run build

      - name: Build Windows installer
        run: |
          cd biosync-launcher
          npm run build:win

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: |
            biosync-launcher/dist-electron/*.exe
            biosync-launcher/dist-electron/*.exe.blockmap
            biosync-launcher/dist-electron/latest.yml
          retention-days: 30

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd biosync-launcher
          npm ci || npm install

      - name: Build React app
        run: |
          cd biosync-launcher
          npm run build

      - name: Build macOS app
        run: |
          cd biosync-launcher
          npm run build:mac
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-installer
          path: |
            biosync-launcher/dist-electron/*.dmg
            biosync-launcher/dist-electron/*.dmg.blockmap
            biosync-launcher/dist-electron/*.zip
            biosync-launcher/dist-electron/latest-mac.yml
          retention-days: 30

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Linux dependencies for electron-builder
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm

      - name: Install dependencies
        run: |
          cd biosync-launcher
          npm ci || npm install

      - name: Build React app
        run: |
          cd biosync-launcher
          npm run build

      - name: Build Linux packages
        run: |
          cd biosync-launcher
          npm run build:linux

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-packages
          path: |
            biosync-launcher/dist-electron/*.AppImage
            biosync-launcher/dist-electron/*.deb
            biosync-launcher/dist-electron/latest-linux.yml
          retention-days: 30

  create-release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/windows-installer/*
            artifacts/macos-installer/*
            artifacts/linux-packages/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
